import AppBar from "@/components/AppBar";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import Footer from "@/components/Footer";
import CartList from "@/components/Cart";
import GLobalContext from "./store/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch("https://dummyjson.com/products/categories");
  const data = await res.json();
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <GLobalContext>
          <AppBar />
          <main className="container mx-auto mt-20">
            <div className="flex row flex-wrap">
              <SideBar data={data} />
              <div className="w-full md:w-3/4">{children}</div>
            </div>
          </main>
          <CartList />
        </GLobalContext>
        <Footer />
      </body>
    </html>
  );
}
